# Generated by Django 4.1.3 on 2022-11-07 01:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("bar_code", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("GAS", "gas"), ("LUZ", "luz")], max_length=20
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("due_date", models.DateTimeField(null=True)),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PAID", "paid"),
                            ("PENDING", "pending"),
                            ("CANCELLED", "canceled"),
                            ("OVERDUE", "overdue"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceStateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.invoice"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.invoicestate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="states",
            field=models.ManyToManyField(
                related_name="invoice",
                through="app.InvoiceStateHistory",
                to="app.invoicestate",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicestatehistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("invoice", "state"),
                name="uniq_invoice_state_active",
            ),
        ),
    ]
