# Generated by Django 4.1.3 on 2022-11-07 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payable",
            fields=[
                ("bar_code", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("GAS", "gas"), ("LUZ", "luz")], max_length=20
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("due_date", models.DateTimeField(null=True)),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayableState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PAID", "paid"),
                            ("PENDING", "pending"),
                            ("CANCELLED", "canceled"),
                            ("OVERDUE", "overdue"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "credit_card"),
                            ("DEBIT_CARD", "debit_card"),
                            ("CASH", "cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("card_number", models.CharField(max_length=16, null=True)),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.payable"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayableStateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.payable"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.payablestate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payable",
            name="states",
            field=models.ManyToManyField(
                related_name="payable",
                through="app.PayableStateHistory",
                to="app.payablestate",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("card_number__isnull", False),
                        ("payment_method__in", ["credit_card", "debit_card"]),
                    ),
                    models.Q(("card_number__isnull", True), ("payment_method", "cash")),
                    _connector="OR",
                ),
                name="check_payment_method_card_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("payable",), name="just_one_payment"
            ),
        ),
        migrations.AddConstraint(
            model_name="payablestatehistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("payable",),
                name="uniq_payable_state_active",
            ),
        ),
    ]
