# Generated by Django 4.1.3 on 2022-11-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoicestatehistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("invoice",),
                name="uniq_invoice_state_active",
            ),
        ),
    ]
