# Generated by Django 4.1.3 on 2022-11-07 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_invoicestatehistory_uniq_invoice_state_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "credit_card"),
                            ("DEBIT_CARD", "debit_card"),
                            ("CASH", "cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("card_number", models.CharField(max_length=16, null=True)),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="invoicestatehistory",
            name="uniq_invoice_state_active",
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app.invoice"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("card_number__isnull", False),
                        ("payment_method__in", ["credit_card", "debit_card"]),
                    ),
                    models.Q(("card_number__isnull", True), ("payment_method", "cash")),
                    _connector="OR",
                ),
                name="check_payment_method_card_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("invoice",), name="just_one_payment"
            ),
        ),
    ]
