# Generated by Django 3.0.4 on 2020-10-15 03:26

from django.db import migrations
from django.utils import timezone

from app.enums import InvoiceStatesEnum


def run(apps, schema_editor):
    InvoiceState = apps.get_model("app", "InvoiceState")
    loaded_states = list(InvoiceState.objects.all().values_list("name", flat=True))
    states = []

    for choice in InvoiceStatesEnum.choices():
        name = choice[1]
        if name not in loaded_states:
            states.append(InvoiceState(name=name))

    InvoiceState.objects.bulk_create(states)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_payment_and_more"),
    ]

    operations = [
        migrations.RunPython(run),
    ]
